# https://github.com/P3TERX/ActionsVM

name: macOS (tmate)

on:
  workflow_dispatch:

jobs:
  Instance:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Run Start Script
      run: source macos-start.sh

    - name: Start SSH via tmate
      uses: P3TERX/ssh2actions@main
